// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA43WC4J-VSqnl36GPARURIJBYCs2v9zoE',
    appId: '1:392680060809:web:77698bd323bb387c999358',
    messagingSenderId: '392680060809',
    projectId: 'ri-and-go-1985b',
    authDomain: 'ri-and-go-1985b.firebaseapp.com',
    storageBucket: 'ri-and-go-1985b.appspot.com',
    measurementId: 'G-3DL7GJ1Q2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4oQMJ6fGqKjorKRXJVxaJPinN-QDmzUg',
    appId: '1:392680060809:android:10f547f256f91146999358',
    messagingSenderId: '392680060809',
    projectId: 'ri-and-go-1985b',
    storageBucket: 'ri-and-go-1985b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYoQpgQsmgYMRSO4Duz47ZG1tiDVxjrDI',
    appId: '1:392680060809:ios:74c103a1d4d5b59e999358',
    messagingSenderId: '392680060809',
    projectId: 'ri-and-go-1985b',
    storageBucket: 'ri-and-go-1985b.appspot.com',
    iosClientId: '392680060809-an9sdv8pi7go5uc45rh6vihe1p7l9brp.apps.googleusercontent.com',
    iosBundleId: 'com.example.infoKino',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYoQpgQsmgYMRSO4Duz47ZG1tiDVxjrDI',
    appId: '1:392680060809:ios:0c64e67dd2fdf60e999358',
    messagingSenderId: '392680060809',
    projectId: 'ri-and-go-1985b',
    storageBucket: 'ri-and-go-1985b.appspot.com',
    iosClientId: '392680060809-ie4bm6e03bkn7o3rssbl699as44p40p1.apps.googleusercontent.com',
    iosBundleId: 'com.example.infoKino.RunnerTests',
  );
}
